/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Returns public configuration for the landing page.
         *     STREAMLIT_URL must be set in .env — e.g. http://localhost:8502
         */
        get: operations["get_config_auth_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Creates a new Organization in the Starter (Free) plan.
         *     Returns the raw API Key — it will NOT be shown again.
         *     After this, the frontend should redirect to the Streamlit dashboard
         *     with ?api_key=<raw_key> so the user is auto-logged-in.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Returns active plans for the landing page pricing section.
         */
        get: operations["list_plans_auth_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensagem
         * @description Envia uma mensagem para o agente do projeto e aguarda a resposta completa. Para streaming token-by-token, use `/chat/message/stream`.
         */
        post: operations["send_message_api_v1_chat_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/message/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensagem com streaming SSE
         * @description Processa a mensagem e retorna a resposta via Server-Sent Events (SSE). O cliente recebe tokens progressivamente para melhor UX.
         */
        post: operations["send_message_stream_api_v1_chat_message_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico da sessão
         * @description Retorna todas as mensagens de uma sessão de conversa.
         */
        get: operations["get_history_api_v1_chat_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/whatsapp/{channel_token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook WhatsApp inbound
         * @description Recebe mensagens de provedores WhatsApp (Chatwoot, Evolution API, N8N). O channel_token na URL identifica e autentica o canal.
         */
        post: operations["whatsapp_inbound_api_v1_webhook_whatsapp__channel_token__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/whatsapp/{channel_token}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerrar sala WhatsApp
         * @description Notifica o AgnoHub que uma sala foi encerrada pelo provedor (N8N, Evolution API, Chatwoot). Limpa a sessão Redis mas preserva o histórico no banco para reuso quando o mesmo número entrar em contato novamente.
         */
        post: operations["whatsapp_close_room_api_v1_webhook_whatsapp__channel_token__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhook/generic/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook genérico
         * @description Endpoint genérico para integrações N8N, Zapier, Make.com, etc.
         */
        post: operations["generic_inbound_api_v1_webhook_generic__channel_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Informações do projeto autenticado
         * @description Retorna informações públicas do projeto associado à API Key.
         */
        get: operations["project_info_api_v1_project_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de conversas do projeto */
        get: operations["list_conversations_api_v1_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_external_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do usuário final */
        get: operations["get_user_profile_api_v1_users__user_external_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza perfil do usuário */
        patch: operations["update_user_profile_api_v1_users__user_external_id__profile_patch"];
        trace?: never;
    };
    "/api/v1/users/{user_external_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conteúdo do MemPalace do usuário */
        get: operations["get_user_memory_api_v1_users__user_external_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista todos os projetos da organização
         * @description Retorna todos os projetos da org autenticada.
         */
        get: operations["list_projects_api_v1_manage_projects_get"];
        put?: never;
        /**
         * Cria um novo projeto
         * @description Cria um novo projeto na organização.
         */
        post: operations["create_project_api_v1_manage_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhes de um projeto */
        get: operations["get_project_api_v1_manage_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Remove um projeto */
        delete: operations["delete_project_api_v1_manage_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Atualiza configurações do projeto */
        patch: operations["update_project_api_v1_manage_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/manage/projects/{project_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista agentes do projeto */
        get: operations["list_agents_api_v1_manage_projects__project_id__agents_get"];
        put?: never;
        /** Cria um agente */
        post: operations["create_agent_api_v1_manage_projects__project_id__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/projects/{project_id}/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhes de um agente */
        get: operations["get_agent_api_v1_manage_projects__project_id__agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Remove um agente */
        delete: operations["delete_agent_api_v1_manage_projects__project_id__agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Atualiza um agente */
        patch: operations["update_agent_api_v1_manage_projects__project_id__agents__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/manage/projects/{project_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista canais do projeto */
        get: operations["list_channels_api_v1_manage_projects__project_id__channels_get"];
        put?: never;
        /** Cria um canal */
        post: operations["create_channel_api_v1_manage_projects__project_id__channels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/projects/{project_id}/channels/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove um canal */
        delete: operations["delete_channel_api_v1_manage_projects__project_id__channels__channel_id__delete"];
        options?: never;
        head?: never;
        /** Atualiza um canal */
        patch: operations["update_channel_api_v1_manage_projects__project_id__channels__channel_id__patch"];
        trace?: never;
    };
    "/api/v1/manage/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista API Keys da organização */
        get: operations["list_api_keys_api_v1_manage_api_keys_get"];
        put?: never;
        /** Gera uma nova API Key */
        post: operations["create_api_key_api_v1_manage_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoga uma API Key */
        delete: operations["revoke_api_key_api_v1_manage_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/manage/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista workspaces da organização */
        get: operations["list_workspaces_api_v1_manage_workspaces_get"];
        put?: never;
        /** Cria um novo workspace */
        post: operations["create_workspace_api_v1_manage_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purchase Credits
         * @description Inicia compra de pacote avulso de créditos.
         *     Retorna URL de pagamento (PIX QR, boleto PDF ou 3DS para cartão).
         */
        post: operations["purchase_credits_api_v1_billing_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe Plan
         * @description Cria assinatura recorrente para um plano pago.
         *     Planos gratuitos são ativados diretamente sem pagamento.
         */
        post: operations["subscribe_plan_api_v1_billing_subscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook/pagarme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pagarme Webhook
         * @description Recebe eventos da Pagar.me e processa pagamentos confirmados.
         *     Configure no painel Pagar.me → Empresa → Webhooks:
         *       URL: https://SEU_DOMINIO/api/v1/billing/webhook/pagarme
         */
        post: operations["pagarme_webhook_api_v1_billing_webhook_pagarme_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Plans
         * @description Lista planos ativos com preço em BRL.
         */
        get: operations["list_plans_api_v1_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Balance
         * @description Retorna saldo de créditos da organização.
         */
        get: operations["get_balance_api_v1_billing_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omnichannel/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receber mensagem de plataforma omnichannel
         * @description Endpoint principal para integração com plataformas omnichannel (Chatwoot, Zendesk, Freshdesk, etc.).
         *
         *     **Modo Síncrono** (`async_mode=false`, padrão):
         *     - Aguarda o processamento e retorna a resposta completa.
         *     - O `room_id` é ecoado na resposta para mapeamento da sala.
         *
         *     **Modo Assíncrono** (`async_mode=true`):
         *     - Retorna `202 Accepted` imediatamente.
         *     - A resposta é entregue via POST no `webhook_url` configurado.
         *     - O payload do webhook contém `session_id = room_id` para mapear a sala.
         *
         *     **Payload do Webhook de Saída:**
         *     ```json
         *     {
         *       "event": "message.completed",
         *       "project_id": "...",
         *       "session_id": "chatwoot_conv_12345",
         *       "user_id": "...",
         *       "message": "mensagem original",
         *       "response": "resposta do agente",
         *       "agent_used": "atendente",
         *       "tokens": {"input": 120, "output": 85, "total": 205},
         *       "latency_ms": 1234,
         *       "timestamp": "2024-01-15T10:30:00Z"
         *     }
         *     ```
         *
         *     **Assinatura do Webhook:**
         *     Se um `webhook_secret` foi configurado, o header `X-AgnoHub-Signature: sha256=<hmac>` é enviado.
         *     Valide com: `HMAC-SHA256(secret, body)`.
         */
        post: operations["receive_omnichannel_message_api_v1_omnichannel_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omnichannel/webhook/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configurar webhook de saída
         * @description Define a URL e o segredo para entrega de respostas via webhook. Use `webhook_secret` para validar a autenticidade das requisições recebidas. Passe `webhook_url=null` para desabilitar o webhook.
         */
        post: operations["configure_webhook_api_v1_omnichannel_webhook_configure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omnichannel/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Testar webhook de saída
         * @description Envia um payload de exemplo para a URL configurada no projeto e retorna o status da entrega. Útil para validar a integração antes de ir para produção.
         */
        get: operations["test_webhook_api_v1_omnichannel_webhook_test_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/omnichannel/webhook/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status do webhook configurado
         * @description Retorna o status atual do webhook de saída do projeto.
         */
        get: operations["webhook_info_api_v1_omnichannel_webhook_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Widget Send
         * @description Endpoint de mensagem para o widget — autenticado por projectId + apiKey no body.
         *     Não requer header X-API-Key (o script no browser não tem como enviar isso com segurança).
         *     Em PREVIEW_MODE (admin), aceita diretamente sem validar a key.
         */
        post: operations["widget_send_widget_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Widget Js
         * @description Serve o script JS que o cliente cola no site.
         */
        get: operations["serve_widget_js_widget_js_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Widget Chat Ui
         * @description Página de chat renderizada dentro do iFrame do widget.
         */
        get: operations["widget_chat_ui_widget_chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/widget/preview/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Widget Preview Page
         * @description Página de preview pública para testar o widget do projeto.
         *     URL: /widget/preview/{project_id}?key=proj_xxx
         *     Gera uma página demo com o widget embutido.
         */
        get: operations["widget_preview_page_widget_preview__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voice/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Configuração de voz do projeto
         * @description Retorna a configuração de voz do projeto para o browser iniciar
         *     uma sessão Gemini Live diretamente (Fase 1 — Browser Direct).
         */
        get: operations["get_voice_config_api_v1_voice_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payload-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista regras de payload do projeto */
        get: operations["list_payload_rules_api_v1_payload_rules_get"];
        put?: never;
        /** Cria nova regra de payload */
        post: operations["create_payload_rule_api_v1_payload_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payload-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualiza regra de payload */
        put: operations["update_payload_rule_api_v1_payload_rules__rule_id__put"];
        post?: never;
        /** Remove regra de payload */
        delete: operations["delete_payload_rule_api_v1_payload_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payload-rules/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reordena prioridade das regras
         * @description Recebe lista de rule_ids na nova ordem e atualiza order_index.
         */
        post: operations["reorder_payload_rules_api_v1_payload_rules_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payload-rules/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Converte instrução NL em regra(s) via IA
         * @description Usa Gemini para converter instrução em linguagem natural em uma
         *     ou mais regras de payload estruturadas.
         */
        post: operations["interpret_rule_from_nl_api_v1_payload_rules_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIKeyCreate */
        APIKeyCreate: {
            /** Name */
            name: string;
            /** Project Id */
            project_id: string;
        };
        /** AgentCreate */
        AgentCreate: {
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Instructions */
            instructions?: string | null;
            /**
             * Model Provider
             * @default google
             */
            model_provider: string;
            /**
             * Model Id
             * @default gemini-2.5-flash
             */
            model_id: string;
            /**
             * Temperature
             * @default 0.5
             */
            temperature: number;
            /**
             * Is Router
             * @default false
             */
            is_router: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /**
             * Add History To Messages
             * @default true
             */
            add_history_to_messages: boolean;
            /**
             * Show Tool Calls
             * @default false
             */
            show_tool_calls: boolean;
            /**
             * Markdown
             * @default true
             */
            markdown: boolean;
            /** Max Tokens */
            max_tokens?: number | null;
        };
        /** AgentUpdate */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Model Provider */
            model_provider?: string | null;
            /** Model Id */
            model_id?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Is Router */
            is_router?: boolean | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Order Index */
            order_index?: number | null;
            /** Add History To Messages */
            add_history_to_messages?: boolean | null;
            /** Show Tool Calls */
            show_tool_calls?: boolean | null;
            /** Markdown */
            markdown?: boolean | null;
            /** Max Tokens */
            max_tokens?: number | null;
        };
        /** ChannelCreate */
        ChannelCreate: {
            /** Name */
            name: string;
            /** Channel Type */
            channel_type: string;
            /**
             * Session Strategy
             * @default user_per_day
             */
            session_strategy: string;
            /** Outbound Webhook Url */
            outbound_webhook_url?: string | null;
            /** Channel Config */
            channel_config?: {
                [key: string]: unknown;
            } | null;
            /** Allowed Domains */
            allowed_domains?: string[] | null;
        };
        /** ChannelUpdate */
        ChannelUpdate: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Outbound Webhook Url */
            outbound_webhook_url?: string | null;
            /** Channel Config */
            channel_config?: {
                [key: string]: unknown;
            } | null;
            /** Allowed Domains */
            allowed_domains?: string[] | null;
            /** Session Strategy */
            session_strategy?: string | null;
        };
        /**
         * ChatHistoryResponse
         * @description Histórico de conversa de uma sessão.
         */
        ChatHistoryResponse: {
            /** Session Id */
            session_id: string;
            /** Messages */
            messages: {
                [key: string]: unknown;
            }[];
            /** Total Messages */
            total_messages: number;
        };
        /**
         * ChatMessageRequest
         * @description Payload de envio de mensagem.
         */
        ChatMessageRequest: {
            /**
             * Message
             * @description Texto da mensagem
             */
            message: string;
            /**
             * User Id
             * @description Identificador do usuário (phone, email, id)
             */
            user_id?: string | null;
            /**
             * Session Id
             * @description ID da sessão existente (para continuar conversa)
             */
            session_id?: string | null;
            /**
             * Channel
             * @description Canal de origem: api | widget | whatsapp
             * @default api
             */
            channel: string;
            /**
             * Metadata
             * @description Dados extras do canal
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Images
             * @description Lista de imagens para chat multimodal. Cada item: {data: base64str, mime_type: str}
             */
            images?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * ChatMessageResponse
         * @description Resposta de uma mensagem processada.
         */
        ChatMessageResponse: {
            /** Job Id */
            job_id: string;
            /** Session Id */
            session_id: string;
            /** Response */
            response: string;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Processing Time Ms
             * @default 0
             */
            processing_time_ms: number;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NLInterpretRequest */
        NLInterpretRequest: {
            /** Instruction */
            instruction: string;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * OmnichannelAsyncResponse
         * @description Resposta assíncrona — a resposta real será entregue via webhook.
         */
        OmnichannelAsyncResponse: {
            /** Job Id */
            job_id: string;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
            /**
             * Message
             * @default Mensagem recebida. A resposta será enviada ao webhook configurado.
             */
            message: string;
        };
        /**
         * OmnichannelMessageRequest
         * @description Mensagem recebida de uma plataforma omnichannel.
         *
         *     O `room_id` é o identificador da conversa/sala na plataforma do cliente
         *     (ex: conversation_id do Chatwoot, ticket_id do Zendesk).
         *     Ele será retornado no webhook de resposta para que a plataforma saiba
         *     em qual sala enviar a mensagem.
         */
        OmnichannelMessageRequest: {
            /**
             * Message
             * @description Texto da mensagem enviada pelo usuário
             * @example Olá, quais são os planos disponíveis?
             */
            message: string;
            /**
             * Room Id
             * @description ID da sala/conversa na plataforma omnichannel. Será ecoado de volta no payload do webhook de resposta.
             * @example chatwoot_conv_12345
             */
            room_id: string;
            /**
             * User Id
             * @description Identificador do usuário na plataforma (phone, email, id)
             * @example +5511999998888
             */
            user_id?: string | null;
            /**
             * Channel
             * @description Identificador do canal de origem
             * @default omnichannel
             * @example chatwoot
             * @example zendesk
             * @example freshdesk
             * @example custom
             */
            channel: string;
            /**
             * Metadata
             * @description Dados extras da plataforma (contact_id, inbox_id, etc.)
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Async Mode
             * @description Se True: retorna 202 imediatamente e envia a resposta via webhook. Se False: aguarda o processamento e retorna a resposta na própria resposta HTTP.
             * @default false
             */
            async_mode: boolean;
        };
        /**
         * OmnichannelMessageResponse
         * @description Resposta síncrona de uma mensagem omnichannel.
         */
        OmnichannelMessageResponse: {
            /** Job Id */
            job_id: string;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /** Response */
            response: string;
            /** Agent Used */
            agent_used?: string | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Processing Time Ms
             * @default 0
             */
            processing_time_ms: number;
            /**
             * Webhook Fired
             * @default false
             */
            webhook_fired: boolean;
            /**
             * Success
             * @default true
             */
            success: boolean;
        };
        /** PayloadRuleCreate */
        PayloadRuleCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Trigger
             * @description Condição de ativação: {field, op, value}
             */
            trigger: {
                [key: string]: unknown;
            };
            /**
             * Action
             * @description Transformação: {type, field, value/from/to}
             */
            action: {
                [key: string]: unknown;
            };
            /**
             * Scope
             * @default both
             */
            scope: string;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Created By Nl */
            created_by_nl?: string | null;
        };
        /** PayloadRuleUpdate */
        PayloadRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Trigger */
            trigger?: {
                [key: string]: unknown;
            } | null;
            /** Action */
            action?: {
                [key: string]: unknown;
            } | null;
            /** Scope */
            scope?: string | null;
            /** Order Index */
            order_index?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** PlanInfo */
        PlanInfo: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Price Usd */
            price_usd: number;
            /** Max Projects */
            max_projects: number;
            /** Max Agents Per Project */
            max_agents_per_project: number;
            /** Monthly Credits */
            monthly_credits: number;
            /** Byok Allowed */
            byok_allowed: boolean;
            /**
             * Is Popular
             * @default false
             */
            is_popular: boolean;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Workspace Id */
            workspace_id?: string | null;
            /**
             * Agno Type
             * @default agent
             */
            agno_type: string;
            /** Team Mode */
            team_mode?: string | null;
            /**
             * Memory Strategy
             * @default hybrid
             */
            memory_strategy: string;
            /**
             * Context Strategy
             * @default adaptive
             */
            context_strategy: string;
            /**
             * Context Window Size
             * @default 10
             */
            context_window_size: number;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Memory Strategy */
            memory_strategy?: string | null;
            /** Context Strategy */
            context_strategy?: string | null;
            /** Context Window Size */
            context_window_size?: number | null;
            /** User Profile Schema */
            user_profile_schema?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** PurchasePackageRequest */
        PurchasePackageRequest: {
            /**
             * Package Id
             * @description ID do pacote, ex: pack_2m
             */
            package_id: string;
            /**
             * Payment Method
             * @default pix
             */
            payment_method: string;
            /** Card Token */
            card_token?: string | null;
            /**
             * Installments
             * @default 1
             */
            installments: number;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Email */
            customer_email?: string | null;
            /** Customer Doc */
            customer_doc?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Org Name */
            org_name?: string | null;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** Org Id */
            org_id: string;
            /** Org Name */
            org_name: string;
            /** Plan */
            plan: string;
            /** Api Key */
            api_key: string;
            /** Dashboard Url */
            dashboard_url: string;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /**
             * Order
             * @description Lista de rule_ids na nova ordem
             */
            order: string[];
        };
        /** SubscribePlanRequest */
        SubscribePlanRequest: {
            /**
             * Plan Id
             * @description UUID do plano da tabela platform_plans
             */
            plan_id: string;
            /**
             * Payment Method
             * @default pix
             */
            payment_method: string;
            /** Card Token */
            card_token?: string | null;
            /** Customer Name */
            customer_name?: string | null;
            /** Customer Email */
            customer_email?: string | null;
            /** Customer Doc */
            customer_doc?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WebhookConfigRequest
         * @description Configuração do webhook de saída do projeto.
         */
        WebhookConfigRequest: {
            /**
             * Webhook Url
             * @description URL que receberá as respostas do agente (HTTPS recomendado)
             * @example https://app.chatwoot.com/webhooks/agnohub
             */
            webhook_url?: string | null;
            /**
             * Webhook Secret
             * @description Segredo para validar a assinatura HMAC-SHA256 (header X-AgnoHub-Signature). Se omitido, não assina.
             */
            webhook_secret?: string | null;
        };
        /** WebhookConfigResponse */
        WebhookConfigResponse: {
            /** Webhook Url */
            webhook_url: string | null;
            /** Has Secret */
            has_secret: boolean;
            /** Test Endpoint */
            test_endpoint: string;
        };
        /** WidgetSendRequest */
        WidgetSendRequest: {
            /**
             * Projectid
             * @description UUID do projeto
             */
            projectId: string;
            /**
             * Apikey
             * @description API Key do projeto (proj_...) ou PREVIEW_MODE
             */
            apiKey: string;
            /** Message */
            message: string;
            /** Sessionid */
            sessionId?: string;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_auth_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_auth_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanInfo"][];
                };
            };
        };
    };
    send_message_api_v1_chat_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_stream_api_v1_chat_message_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_v1_chat_history_get: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_inbound_api_v1_webhook_whatsapp__channel_token__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatsapp_close_room_api_v1_webhook_whatsapp__channel_token__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generic_inbound_api_v1_webhook_generic__channel_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_info_api_v1_project_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_conversations_api_v1_conversations_get: {
        parameters: {
            query?: {
                session_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_v1_users__user_external_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_profile_api_v1_users__user_external_id__profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_memory_api_v1_users__user_external_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_external_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_manage_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_project_api_v1_manage_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_manage_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_manage_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_manage_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_manage_projects__project_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_api_v1_manage_projects__project_id__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_v1_manage_projects__project_id__agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_v1_manage_projects__project_id__agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_v1_manage_projects__project_id__agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_channels_api_v1_manage_projects__project_id__channels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_channel_api_v1_manage_projects__project_id__channels_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_channel_api_v1_manage_projects__project_id__channels__channel_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_channel_api_v1_manage_projects__project_id__channels__channel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChannelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_manage_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_api_key_api_v1_manage_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_v1_manage_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_api_v1_manage_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_workspace_api_v1_manage_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purchase_credits_api_v1_billing_purchase_post: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchasePackageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subscribe_plan_api_v1_billing_subscribe_post: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pagarme_webhook_api_v1_billing_webhook_pagarme_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_plans_api_v1_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_balance_api_v1_billing_balance_get: {
        parameters: {
            query?: never;
            header: {
                "X-Org-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_omnichannel_message_api_v1_omnichannel_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OmnichannelMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OmnichannelMessageResponse"] | components["schemas"]["OmnichannelAsyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    configure_webhook_api_v1_omnichannel_webhook_configure_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_webhook_api_v1_omnichannel_webhook_test_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    webhook_info_api_v1_omnichannel_webhook_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    widget_send_widget_send_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WidgetSendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_widget_js_widget_js_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    widget_chat_ui_widget_chat_get: {
        parameters: {
            query?: {
                projectId?: string;
                apiKey?: string;
                sessionId?: string;
                theme?: string;
                primaryColor?: string;
                botName?: string;
                greeting?: string;
                avatarUrl?: string;
                apiBase?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    widget_preview_page_widget_preview__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_config_api_v1_voice_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_payload_rules_api_v1_payload_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_payload_rule_api_v1_payload_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayloadRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_payload_rule_api_v1_payload_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PayloadRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_payload_rule_api_v1_payload_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_payload_rules_api_v1_payload_rules_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_rule_from_nl_api_v1_payload_rules_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NLInterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
